language: scala
scala:
  - 2.10.4
  - 2.11.8
jdk:
  - oraclejdk7
  - openjdk7
script: travis_retry ./build.sh
env:
  global:
    secure: hpPBGkOeeVcej9tdlZkem2WSZLxZRin0ttAVh8vTBjQc8gZOrogfKRMd9MS9kUQJr3HVFiOaQLLEQyJaZXkDEmHyJAVjnUymW5VjSRYS3SpjTEV9XQqU6sfPBjUTjetnc4CwTXjlkm64AU7gaJlc/fM/eURg3nOxc0P8YXrW37s=
